[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"
name = "minisynth"
version = "0.1.0"

[build-dependencies]
lalrpop = "0.16.1"

[dependencies]
failure = "0.1.3"
id-arena = "1.0.0"
lalrpop-util = "0.16.1"
regex = "1.0.6"
z3 = { git = "https://github.com/fitzgen/z3-rs" }
